language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
  provider: surge
  login: allenclark@u.boisestate.edu
  project: ./dist
  domain: yotenki.surge.com
  on:
    branch: master
  edge: true # opt in to dpl v2